### ISSUE TITLE
How made config file

### ISSUE THREAD

**Issue by vinsilsim** [reecube/node-pokemon-go-map-server#1]
Hello Dev, 
I became interested in his most did not understand repository as still run!

Can you post easy install/run?

**Comment by reecube** [comment]
https://github.com/reecube/node-pokemon-go-map-server/blob/master/README.md
1. `run npm install`
2. copy `./server/config/config-default.json` => `./server/config/config.json`
3. change the TODO-values in the config file and add at least one account (format is described in the README.md file)
4. run the server with `node .`
